spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/timesheet_db
    username: timesheet_user
    password: timesheet_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: your-256-bit-secret
  expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
